book:
    title:            "JavaScript"
    author:           "Arkaitz Garro"
    edition:          "Primera edición"
    language:         es
    publication_date: ~

    generator: { name: easybook, version: 5.0-DEV }

    contents:
        # available content types: acknowledgement, afterword, appendix, author,
        # chapter, conclusion, cover, dedication, edition, epilogue, foreword,
        # glossary, introduction, license, lof (list of figures), lot (list of
        # tables), part, preface, prologue, title, toc (table of contents)
        - { element: cover }
        - { element: edition }
        - { element: license, content: 00_Licencia.md }
        - { element: toc   }
        - { element: chapter, number: 1, content: 01_Introduccion.md }
        - { element: chapter, number: 2, content: 02_Primer_script.md }
        - { element: chapter, number: 3, content: 03_Sintaxis_basica.md }
        - { element: chapter, number: 4, content: 04_Operadores.md }
        - { element: chapter, number: 5, content: 05_Estructuras_de_control.md }
        - { element: chapter, number: 6, content: 06_Funciones_propiedades_basicas.md }
        - { element: chapter, number: 7, content: 07_Funciones.md }
        - { element: chapter, number: 8, content: 08_Objetos.md }
        - { element: chapter, number: 9, content: 09_Herencia.md }
        - { element: chapter, number: 10, content: 10_Arrays.md }
        - { element: chapter, number: 11, content: 11_RegExp.md }
        - { element: chapter, number: 12, content: 12_JSON.md }
        - { element: chapter, number: 13, content: 13_DOM.md }
        - { element: chapter, number: 14, content: 14_BOM.md }
        - { element: chapter, number: 15, content: 15_Eventos.md }
        - { element: chapter, number: 16, content: 16_Formularios.md }
        - { element: chapter, number: 17, content: 17_Otras_utilidades.md }
        - { element: chapter, number: 18, content: 18_Ejercicios.md }

    editions:
        #ebook:
        #    format:         epub
        #    highlight_code: false
        #    include_styles: true
        #    labels:         ['appendix', 'chapter']  # labels also available for: "figure", "table"
        #    theme:          clean
        #    toc:
        #        deep:       1
        #        elements:   ["appendix", "chapter", "part"]

        print:
            format:         pdf
            highlight_cache: true
            highlight_code: true
            include_styles: true
            isbn:           ~
            labels:         ["appendix", "chapter"]  # labels also available for: "figure", "table"
            margin:
                top:        25mm
                bottom:     25mm
                inner:      30mm
                outter:     20mm
            page_size:      A4
            theme:          clean
            toc:
                deep:       2
                elements:   ["appendix", "chapter", "part"]
            two_sided:      true

        web:
            format:         html
            highlight_cache: true
            highlight_code: true
            include_styles: true
            labels:         ["appendix", "chapter"]  # labels also available for: "figure", "table"
            theme:          clean
            toc:
                deep:       2
                elements:   ["appendix", "chapter"]

        website:
            extends:        web
            format:         html_chunked
