book:
    title:            "Responsive Web Design"
    author:           "Arkaitz Garro"
    edition:          "Primera edición"
    language:         es
    publication_date: ~

    generator: { name: easybook, version: 5.0-DEV }

    contents:
        # available content types: acknowledgement, afterword, appendix, author,
        # chapter, conclusion, cover, dedication, edition, epilogue, foreword,
        # glossary, introduction, license, lof (list of figures), lot (list of
        # tables), part, preface, prologue, title, toc (table of contents)
        - { element: cover }
        - { element: edition }
        - { element: license, content: 00_Licencia.md }
        - { element: toc   }
        - { element: chapter, number: 1, content: 01_Introduccion.md }
        - { element: chapter, number: 2, content: 02_Grid.md }
        - { element: chapter, number: 3, content: 03_Imagenes.md }
        - { element: chapter, number: 4, content: 04_Media_Query.md }
        - { element: chapter, number: 5, content: 05_Desarrollo.md }
        - { element: chapter, number: 6, content: 06_Ejercicios.md }


    editions:
        #ebook:
        #    format:         epub
        #    highlight_code: false
        #    include_styles: true
        #    labels:         ['appendix', 'chapter']  # labels also available for: "figure", "table"
        #    theme:          clean
        #    toc:
        #        deep:       1
        #        elements:   ["appendix", "chapter", "part"]

        print:
            format:         pdf
            highlight_cache: true
            highlight_code: true
            include_styles: true
            isbn:           ~
            labels:         ["appendix", "chapter"]  # labels also available for: "figure", "table"
            margin:
                top:        25mm
                bottom:     25mm
                inner:      30mm
                outter:     20mm
            page_size:      A4
            theme:          clean
            toc:
                deep:       2
                elements:   ["appendix", "chapter", "part"]
            two_sided:      true

        web:
            format:         html
            highlight_cache: true
            highlight_code: true
            include_styles: true
            labels:         ["appendix", "chapter"]  # labels also available for: "figure", "table"
            theme:          clean
            toc:
                deep:       2
                elements:   ["appendix", "chapter"]

        website:
            extends:        web
            format:         html_chunked
